import type { Game } from '../data/types';

export const quickGame: Game = {
  name: 'Quick Game',
  slug: 'quick-game',
  img: '/images/quick-game.webp',
  rules: '/rules/quick-game.pdf',
  players: '2–4',
  min: 2,
  max: 4,
  dur: '10 min',
  mins: 10,
  cat: 'quick',
  group: 'party',
  kw: ['card-game', 'family'],
  short: 'A quick card game.',
  desc: 'A fast-paced card game for the whole family.',
  detail: '<div class="detail-section"><h3>How to Play</h3><p>Play cards fast.</p></div>',
  yt: 'how to play quick game',
};

export const mediumGame: Game = {
  name: 'Medium Game',
  slug: 'medium-game',
  img: '/images/medium-game.webp',
  rules: '/rules/medium-game.pdf',
  players: '3–6',
  min: 3,
  max: 6,
  dur: '45 min',
  mins: 45,
  cat: 'medium',
  group: 'strat',
  kw: ['strategy', 'classic'],
  short: 'A medium strategy game.',
  desc: 'A classic strategy game with moderate playtime.',
  detail: '<div class="detail-section"><h3>Strategy</h3><p>Think hard.</p></div>',
  yt: 'how to play medium game',
};

export const longGame: Game = {
  name: 'Long Game',
  slug: 'long-game',
  img: '/images/long-game.webp',
  rules: '/rules/long-game.pdf',
  players: '2–5',
  min: 2,
  max: 5,
  dur: '2 hrs',
  mins: 120,
  cat: 'long',
  group: 'coop',
  kw: ['cooperative', 'thematic'],
  short: 'A long cooperative game.',
  desc: 'An epic cooperative adventure lasting hours.',
  detail: '<div class="detail-section"><h3>Adventure</h3><p>Work together.</p></div>',
  yt: 'how to play long game',
};

export const bananagramsGame: Game = {
  name: 'Bananagrams',
  slug: 'bananagrams',
  img: '/images/bananagrams.webp',
  rules: '/rules/bananagrams.pdf',
  players: '2–8',
  min: 2,
  max: 8,
  dur: '15 min',
  mins: 15,
  cat: 'quick',
  group: 'word',
  kw: ['word', 'family', 'quick-play'],
  short: 'A fast word game.',
  desc: 'Race to build your own crossword grid.',
  detail: '<div class="detail-section"><h3>How to Play</h3><p>Build words fast.</p></div>',
  yt: 'how to play bananagrams',
};

export const sevenWondersGame: Game = {
  name: '7 Wonders',
  slug: '7-wonders',
  img: '/images/7-wonders.webp',
  rules: '/rules/7-wonders.pdf',
  players: '2–7',
  min: 2,
  max: 7,
  dur: '30 min',
  mins: 30,
  cat: 'medium',
  group: 'strat',
  kw: ['strategy', 'card-game'],
  short: 'A card drafting civilization game.',
  desc: 'Draft cards to build your ancient civilization.',
  detail: '<div class="detail-section"><h3>Strategy</h3><p>Draft wisely.</p></div>',
  yt: 'how to play 7 wonders',
};

export const testGames: Game[] = [quickGame, mediumGame, longGame];
