// Fetch each game's difficulty from BoardGameGeek: the community's average
// weight (1 light to 5 heavy) for every game and game-inside-a-game in
// src/data/games.ts that carries a BGG id (`bgg`), written to the id ->
// weight map in src/data/gameWeights.ts that games.ts merges in.
//
//   npm run game-weights
//
// The site's own endpoint answers by id without a token, as for the
// wishlist's box art (scripts/fetch-wishlist-art.ts). A game BGG has no
// weight votes for is kept as null, and shows no difficulty. A run cut
// short by a rate limit or an outage keeps the weights it had for the games
// it didn't reach; ids no longer in games.ts are dropped.
import { readFile, writeFile } from 'node:fs/promises';

const MAP_FILE = 'src/data/gameWeights.ts';
const STATS_URL = (bgg: number) => `https://api.geekdo.com/api/dynamicinfo?objectid=${bgg}&objecttype=thing`;

interface Stats { avgweight?: string; numweights?: string }

// The games are data literals; read them straight off the source rather
// than importing it (its path-less imports are Vite's, not Node's). Every
// game and game inside one has its name and slug before its id.
const source = await readFile('src/data/games.ts', 'utf8');
const games = [...source.matchAll(/\bname:"([^"]+)",\s*slug:"[^"]+"[^\n]*?\bbgg:(\d+)/g)]
  .map((m) => ({ name: m[1], bgg: Number(m[2]) }));
if (games.length === 0) throw new Error('no BoardGameGeek ids found in src/data/games.ts');

// What the last run fetched, for the games this one doesn't reach.
const previous = new Map<number, number | null>();
try {
  for (const m of (await readFile(MAP_FILE, 'utf8')).matchAll(/^\s*(\d+): ([\d.]+|null),/gm)) {
    previous.set(Number(m[1]), m[2] === 'null' ? null : Number(m[2]));
  }
} catch {
  // No map yet.
}

const weights = new Map<number, number | null>();
let stopped = false;
for (const { name, bgg } of games) {
  if (stopped) {
    const kept = previous.get(bgg);
    if (kept !== undefined) weights.set(bgg, kept);
    continue;
  }
  const r = await fetch(STATS_URL(bgg));
  if (r.status === 429) {
    console.error(`BoardGameGeek is rate limiting (429) at ${name}; keeping the last weights for the rest, re-run later.`);
    stopped = true;
    const kept = previous.get(bgg);
    if (kept !== undefined) weights.set(bgg, kept);
    continue;
  }
  let stats: Stats | undefined;
  try {
    stats = r.ok ? ((await r.json()) as { item?: { stats?: Stats } }).item?.stats : undefined;
  } catch {
    // Not JSON: treated as no answer below.
  }
  const weight = Number(stats?.avgweight);
  if (!stats) {
    console.warn(`no answer for ${name} (BGG ${bgg}, ${r.status}); keeping its last weight`);
    const kept = previous.get(bgg);
    if (kept !== undefined) weights.set(bgg, kept);
  } else if (Number(stats.numweights) > 0 && weight >= 1 && weight <= 5) {
    weights.set(bgg, Math.round(weight * 100) / 100);
    console.log(`${name}: ${weight.toFixed(2)} (${stats.numweights} votes)`);
  } else {
    weights.set(bgg, null);
    console.warn(`${name} (BGG ${bgg}) has no weight votes; it shows no difficulty`);
  }
  // BGG asks clients to keep a gentle pace.
  await new Promise((resolve) => setTimeout(resolve, 1200));
}

const named = new Map(games.map((g) => [g.bgg, g.name]));
const lines = [...weights.keys()].sort((a, b) => a - b).map((id) => `  ${id}: ${weights.get(id)}, // ${named.get(id)}`).join('\n');
await writeFile(MAP_FILE, `// Generated by \`npm run game-weights\` (scripts/fetch-game-weights.ts):
// BoardGameGeek's average weight, 1 (light) to 5 (heavy), for each game in
// games.ts with a BGG id, by that id; null where BGG has no weight votes.
// Those, and games missing here, show no difficulty. Do not edit by hand;
// re-run the script.
export const GAME_WEIGHTS: Record<number, number | null> = {
${lines}
};
`);
console.log(`${[...weights.values()].filter((w) => w !== null).length} of ${games.length} games have a weight.`);
