// Fetch box art for the compiled-in wishlist from BoardGameGeek and bundle
// it: one file per entry under public/images/wishlist/ plus the id -> path
// map in src/data/wishlistArt.ts that wishlist.ts merges in.
//
//   BGG_API_TOKEN=... npm run wishlist-art
//
// Needs the same token the API uses (BGG answers 401 without one). Entries
// that already have a file are skipped, so re-running only fills gaps; pass
// --refresh to refetch everything. Suggestions get their art at approval
// time through the same lookup, not here.
import { mkdir, readFile, writeFile, access } from 'node:fs/promises';
import { lookupGame } from '../api/_lib/bgg.ts';

const token = process.env.BGG_API_TOKEN;
if (!token) {
  console.error('BGG_API_TOKEN is not set; register for one at boardgamegeek.com and export it first.');
  process.exit(1);
}
const refresh = process.argv.includes('--refresh');
const ART_DIR = 'public/images/wishlist';
const MAP_FILE = 'src/data/wishlistArt.ts';

// The entries are data literals; read the ids and names straight off the
// source rather than importing it (its path-less imports are Vite's, not Node's).
const source = await readFile('src/data/wishlist.ts', 'utf8');
const entries = [...source.matchAll(/\{\s*id:"([^"]+)",\s*name:"([^"]+)"/g)].map((m) => ({ id: m[1], name: m[2] }));
if (entries.length === 0) throw new Error('no wishlist entries found in src/data/wishlist.ts');

// One probe first: the lookup reads every non-200 as "no match", which
// would turn a rejected token or a rate limit into a page of misleading
// warnings and a rewritten map.
const probe = await fetch('https://boardgamegeek.com/xmlapi2/thing?id=13', { headers: { Authorization: `Bearer ${token}` } });
if (probe.status === 401) {
  console.error('BoardGameGeek rejected BGG_API_TOKEN (401). Check the token and try again.');
  process.exit(1);
}
if (probe.status === 429) {
  console.error('BoardGameGeek is rate limiting this token (429). Wait a while and try again.');
  process.exit(1);
}

await mkdir(ART_DIR, { recursive: true });
const existing = /export const WISHLIST_ART[^{]*(\{[\s\S]*?\});/.exec(await readFile(MAP_FILE, 'utf8'))?.[1] ?? '{}';
const art: Record<string, string> = refresh ? {} : (Function(`return (${existing})`)() as Record<string, string>);

for (const { id, name } of entries) {
  if (art[id] && !refresh && await access(`public${art[id]}`).then(() => true, () => false)) continue;
  const details = await lookupGame(name, fetch, 15_000, token);
  if (!details?.img) {
    console.warn(`no art for ${name} (${details ? 'entry has no thumbnail' : 'no confident BGG match'})`);
    continue;
  }
  const r = await fetch(details.img);
  if (!r.ok) {
    console.warn(`could not download art for ${name}: ${r.status}`);
    continue;
  }
  const ext = /\.(png|webp)(?:$|\?)/i.exec(details.img)?.[1]?.toLowerCase() ?? 'jpg';
  const file = `${ART_DIR}/${id}.${ext}`;
  await writeFile(file, Buffer.from(await r.arrayBuffer()));
  art[id] = `/images/wishlist/${id}.${ext}`;
  console.log(`${name}: ${art[id]}`);
  // BGG asks clients to keep a gentle pace.
  await new Promise((resolve) => setTimeout(resolve, 1200));
}

const lines = Object.keys(art).sort().map((id) => `  '${id}': '${art[id]}',`).join('\n');
await writeFile(MAP_FILE, `// Generated by \`npm run wishlist-art\` (scripts/fetch-wishlist-art.ts): the
// bundled box-art file for each compiled-in wishlist entry, by id. Entries
// missing here render without art. Do not edit by hand; re-run the script.
export const WISHLIST_ART: Record<string, string> = {
${lines}
};
`);
console.log(`${Object.keys(art).length} of ${entries.length} entries have art.`);
