// Generated by `npm run game-weights` (scripts/fetch-game-weights.ts):
// BoardGameGeek's average weight, 1 (light) to 5 (heavy), for each game in
// games.ts with a BGG id, by that id; null where BGG has no weight votes.
// Those, and games missing here, show no difficulty. Do not edit by hand;
// re-run the script.
export const GAME_WEIGHTS: Record<number, number | null> = {
  13: 2.28, // Catan
  181: 2.06, // Risk
  592: 2.03, // Spades
  891: 1.42, // Cranium
  1111: 1.2, // Taboo
  1692: 1.08, // Spoons
  2223: 1.1, // Uno
  6887: 1.74, // Hearts
  6901: 1.69, // Euchre
  7682: 1.05, // Go Fish
  9209: 1.82, // Ticket to Ride
  10400: 1.18, // Klondike Solitaire
  11017: 1.06, // Crazy Eights
  14996: 1.92, // Europe
  15712: 1.19, // Egyptian Ratscrew
  15878: 1.39, // Rummy
  17521: 1.25, // Golf
  27225: 1.29, // Bananagrams
  30549: 2.39, // Pandemic
  50381: 1.17, // Cards Against Humanity
  68448: 2.31, // 7 Wonders
  92302: 1, // Analyze Me
  147949: 1.38, // One Night Werewolf
  172225: 1.08, // Exploding Kittens
  178900: 1.25, // Codenames
  181304: 1.89, // Mysterium
  199042: 2.09, // Hogwarts Battle
  204886: 1.82, // Suspicion
  209418: 2.18, // Dominion
  230802: 1.77, // Azul
  249816: 1, // Taco vs Burrito
  253664: 1.03, // Taco Goat Cheese Pizza
  274533: 1.09, // Throw Throw Burrito
  277085: 1.13, // Love Letter
  300358: 1, // Speed
  312786: 1.11, // Poetry for Neanderthals
  318632: 1, // For the Girls
};
