// Generated by `npm run wishlist-art` (scripts/fetch-wishlist-art.ts): the
// bundled box-art file for each compiled-in wishlist entry, by id. Entries
// missing here render without art. Do not edit by hand; re-run the script.
export const WISHLIST_ART: Record<string, string> = {};
